### PR TITLE
added a check with getimagesize

### PR DESCRIPTION
**Pull request by horst-n**
If `exif_imagetype` is not available one can use `getimagesize` before guessing with the `fileextension`

### CODE REVIEW

**Comment by Gregwar** [comment]
Hello,
As can be seen in #124 (which I don't know why it was closed just after opened), this is not mergeable anymore.

Moreover, calling this method implies you will have to open the original file to check its contents, which is not required by the extension method. As an effect, displaying a page with a lot of cached image results in zero files to open with current code and each original images might have to be opened with your implementation.

That is why I'm not convinced about this approach

**Comment by Gregwar** [comment]
(Though, feel free to give other arguments, and maybe you'll want to have this guess style as an option as well)

**Comment by horst-n** [comment]
Hi, 
your decision makes sense. My code was meant as a suggestion / fallback for cases where the always invoked function "exif_imagetype" is missing. 

As I understand it, the function "exif_imagetype" opens the image files every time too, but is faster, as it reads a smaller part of the metadata then the function "getimagesize" does. My suggestion should make it more robust, but only adds value in the rare cases where the exif_imagetype function is missing AND there are image files that have the wrong file extension. Maybe this is to rare in the wild, that this can (or better:) should be ignored, in favor for the 99.99999% of all cases (with right extensions in the filenames) can run much faster.  :-)

**Comment by kicken** [comment]
> (which I don't know why it was closed just after opened), 

@Gregwar for what it's worth, the request was open for 3 years, I didn't just open it then close it.  I no longer had a need for the change and got tired of looking at it.  Since it seemed no one cared, I closed it.

It's been a long time but if I remember right, the reason I wanted the change is because I was dealing with a case where the file names were random and had no extension to use for a guess and I also did not have the exif function available.  Adding getimagesize seemed appropriate as yet another way to guess vs just defaulting to jpeg.

I suppose there's an argument to be made for speed where it might be worth just looking at the extension first for speed and doing getimagesize as a final attempt.  I could make that change if you think you'd accept it, otherwise I won't waste my time again.

**Pull request closed without merging**
