### PR TITLE
Add test by Github Actions

### PR DESCRIPTION
**Pull request by Rotzbua**
Travis does not offer an easy free tier for open source, so I replaced it by the new Github Action service.
I did not got the end of life php versions running properly, so dropped them. Before the usual complains: people with eol php can still use the older lib versions.
Best wishes

Changes:
* Remove travis
* Use current phpunit 9
* Bump min php to 7.3
* Test php 7.3, 7.4, 8.0, 8.1
* Fix link to gregware.com

### CODE REVIEW

**Comment by Chris53897** [comment]
Looks good at first sight.
@Gregwar Is there any chance this is getting merged?

**Comment by Gregwar** [comment]
Looks good to me too.

Just one question, can you comment on the practice of using `self::assertSame` instead of `$this->assertSame` ?
I understand that the method is indeed static and that it is just a question of practice, but, from the official `phpunit` latest documentation, `$this->` is used:
https://phpunit.readthedocs.io/fr/latest/assertions.html#assertsame

**Comment by Chris53897** [comment]
This if often detected by the IDE, and an auto-suggestion. In my Case PhpStorm and i apply them very often.
That is maybe the reason, too for @Rotzbua

**Comment by Gregwar** [comment]
Ok, actually PHPUnit says it's fine to use static version as well (https://phpunit.readthedocs.io/en/9.5/assertions.html)
Thanks for contributing!

**Comment by Chris53897** [comment]
Thanks. Now it is easier to send new PR.

**Pull request merged**
