### PR TITLE
Silence EXIF errors

### PR DESCRIPTION
**Pull request by bytespider**
Don't break the entire resize operation, for one small EXIF error, which may not even stop us from rotating the image.

Fixes issues #92 and #96

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
How to be sure the image is OK even if `exif_read_data` fails?

**Comment by bytespider** [comment]
`exif_read_data` returns false if there is no EXIF data, and I'm not convinced corrupt exif data renders the image unusable.

**Comment by Soullivaneuh** [comment]
In this case you should manage `false` return of `exif_read_data`. In this case, the code will broke just after that (array access).

**Comment by Soullivaneuh** [comment]
And, IMHO, ignore `exif_read_data` should be a configurable option.

**Comment by garygreen** [comment]
New PR #121 fixes with the proper `false` check.

**Comment by garygreen** [comment]
@Gregwar @Soullivaneuh this one can be closed as fixed in #121

**Pull request closed without merging**
