### PR TITLE
Progressive PNG / JPEG

### PR DESCRIPTION
**Pull request by wodka**
-> add the call to the image adapter

### CODE REVIEW

**Comment by CharlyPoppins** [comment]
Hi, I can't found how to use it.

**Comment by wodka** [comment]
call the function enableProgressive() on a GD Adapter

**Comment by CharlyPoppins** [comment]
so with the ImageBundle it works like image(path/to/my/image).crop(1,2,3,4).enableProgressive().jpg(80) ?

**Comment by wodka** [comment]
have you even tried it befor you asked? 

the image() twig extension should return you an imageHandler instance -> that one will forward it to the adapter (https://github.com/Gregwar/Image/blob/master/Image.php#L357)

it also only works if you use GD

**Comment by CharlyPoppins** [comment]
Tried but I'm not sure something changed, I'm gonna check if I use GD.

**Pull request merged**
